name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: importantimport/.github/.github/workflows/pnpm-install.yml@main
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: pnpm -r -F "./packages/**" build

      - name: Publish
        run: pnpm -r -F "./packages/**" publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
